---
title: "Assignment4"
author: "Cari Lewis"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: yeti
    highlight: tango
    df_print: tibble
---
  
### Load the required packages, download the data, and import it into the `R` environment.  
  
```{R}
# load tidyverse
library(tidyverse)

# download and import the data
Matt_ebird <- read_csv("https://github.com/mbtoomey/Biol_7263/blob/main/Data/MBT_ebird.csv?raw=true")

# view the headers
glimpse(Matt_ebird)
```

### 1. In which year did I observe the most individual birds? How many?  
  
```{R}
# create a group by year
Matt_ebird <- group_by(Matt_ebird, year)

# summarize the 'count_tot' variable by year groups
summarize(Matt_ebird, max_bird=max(count_tot, na.rm = TRUE))
```

## *In `r slice_max(summarize(Matt_ebird, max_bird=max(count_tot, na.rm=TRUE)), max_bird)` birds were recorded.*  

### 2. In that year how many different species of birds did I observe?  
  
```{R}
# ungroup by year
ungroup(Matt_ebird)

# pull out all 2020 data
Matt_ebird_2020 <- filter(Matt_ebird, year == "2020")

# group by species
Matt_ebird_2020 <- group_by(Matt_ebird_2020, scientific_name)

# print the dimensions of the table produced from summarizing by scientific name
dim(summarize(Matt_ebird_2020))
```
  
## *There are `r dim(summarize(Matt_ebird_2020))[1]` species recorded for 2020.*  
  
### 3. In which state did I most frequently observe Red-winged Blackbirds?  
  
```{R}
# pull out all Red-winged blackbird observations
Matt_ebird_RWBB <- filter(Matt_ebird, common_name == "Red-winged Blackbird")

# group by location
Matt_ebird_RWBB <-group_by(Matt_ebird_RWBB, location)

# summarize the data by location
summarise(Matt_ebird_RWBB, state_total=sum(count_tot))
```
  
## *The most Red-winged Blackbirds were observed in `r slice_max(summarize(Matt_ebird_RWBB, state_total=sum(count_tot), na.rm=TRUE), state_total)[1]`.*  
  
### 4. Filter observations for a duration between 5 and 200 minutes. Calculate the mean rate per checklist that I encounter species each year. Specifically, calculate the number of species in each checklist divided by duration and then take the mean for the year.  
  
```{r}
# create a new dataset by filtering observations for duration between 5-200 minutes
Matt_ebird_duration <- filter(Matt_ebird, duration > 5 & duration < 200)

# group by list_ID (which I think is "checklist")
Matt_ebird_duration <- group_by(Matt_ebird_duration, list_ID)

# create a new variable `rate` for each list_ID
Matt_ebird_duration <- mutate(Matt_ebird_duration, rate = (count/duration))

# ungroup and group by year
ungroup(Matt_ebird_duration)

Matt_ebird_duration <- group_by(Matt_ebird_duration, year)

# calculate the mean rate of species encountered by year
summarise(Matt_ebird_duration, mean_rate=mean(rate))
```

### 5. Create a tibble that includes the complete observations for the top 10 most frequently observed species. First generate a top 10 list and then use this list to filter all observations. Export this tibble as a `.csv` file saved to a folder called “Results” folder within your R project and add link to the markdown document.  
  
```{R, eval = FALSE}
# group by species
Matt_ebird <- group_by(Matt_ebird, scientific_name)

# create a top 10 list
ebird_top_10 <- head(arrange(summarise(Matt_ebird, freq=sum(count)), by = desc(freq)),10)

# filter the original dataset using the top 10 list
F1 <- filter(Matt_ebird, scientific_name == ebird_top_10[1,1])
F2 <- filter(Matt_ebird, scientific_name == ebird_top_10[2,1])
F3 <- filter(Matt_ebird, scientific_name == ebird_top_10[3,1])
F4 <- filter(Matt_ebird, scientific_name == ebird_top_10[4,1])
F5 <- filter(Matt_ebird, scientific_name == ebird_top_10[5,1])
F6 <- filter(Matt_ebird, scientific_name == ebird_top_10[6,1])
F7 <- filter(Matt_ebird, scientific_name == ebird_top_10[7,1])
F8 <- filter(Matt_ebird, scientific_name == ebird_top_10[8,1])
F9 <- filter(Matt_ebird, scientific_name == ebird_top_10[9,1])
F10 <- filter(Matt_ebird, scientific_name == ebird_top_10[10,1])

# merge all the top ten datasets into a 'csv' saved in the Results folder
write_csv(full_join(F1, 
                    full_join(F2, 
                              full_join(F3, 
                                        full_join(F4, 
                                                  full_join(F5, 
                                                            full_join(F6, 
                                                                      full_join(F7, 
                                                                                full_join(F8, 
                                                                                          full_join(F9, F10))))))))), 
          "Results/ebird_top10.csv")
```
  
### Click [Top_10_Bird_Obs](Results/ebird_top10.csv) to download the output `.csv` file.  
